サイトのガワを作った
ueckoken/chofu-race-course pull request #14
Opened 2022-09-08 16:54 UTC by hutinoatari

レース/馬のデータはハードコーディング

2022-09-08 17:06 UTC, Azuki-bar approved these changes
LGTM with nitsです

2022-09-08 17:06 UTC, Azuki-bar commented on frontend/src/types/api.ts
> +    stert: number;
typo

2022-09-08 17:06 UTC, Azuki-bar commented on frontend/src/types/api.ts
> +    history: {
配列なら `histories`にしませんか？

2022-09-08 17:06 UTC, Azuki-bar commented on frontend/src/types/api.ts
> +    member: {
配列ならmembersにしませんか？

2022-09-08 17:22 UTC, Azuki-bar commented on frontend/src/types/api.ts
> +export type RaceData = {
question
protobufが生成した型を使っていない理由ってあるんですか？

2022-09-08 17:51 UTC, Azuki-bar requested changes
clientってディレクトリに全て押し込むつもりでした
ディレクトリどう切るかは一度話しましょう

2022-09-09 14:57 UTC, hutinoatari commented on frontend/src/types/api.ts
> +    stert: number;
sorry......

2022-09-09 14:57 UTC, hutinoatari commented on frontend/src/types/api.ts
> +    history: {
するぞ！

2022-09-09 14:57 UTC, hutinoatari commented on frontend/src/types/api.ts
> +    member: {
するぞ！

2022-09-09 14:59 UTC, hutinoatari commented on frontend/src/types/api.ts
> +export type RaceData = {
connect-webの役割を勘違いしてた、次からは恩恵に預かります

2022-09-09 16:19 UTC, hutinoatari commented
非推奨属性を使っていたのが原因だった、ごめんなさい

2022-09-11 08:03 UTC, Azuki-bar commented on .github/workflows/check_ts.yaml
> +      - run: |
@Azuki-bar   working directoryを指定するようにする

2022-09-11 08:10 UTC, Azuki-bar approved these changes

2022-09-11 09:04 UTC, merged