レース結果消すapiを定義
ueckoken/chofu-race-course pull request #293
Opened 2022-11-10 16:08 UTC by hutinoatari

close #291

2022-11-10 16:14 UTC, Azuki-bar requested changes

2022-11-10 16:14 UTC, Azuki-bar commented on proto/spec/v1/userdata.proto
> +  rpc EraseRace(EraseRaceRequest) returns (EraseRaceResponse) {}
というかレース結果削除は `DeleteRaceResult`ですね

2022-11-11 16:52 UTC, hutinoatari commented on proto/spec/v1/userdata.proto
> +  rpc EraseRace(EraseRaceRequest) returns (EraseRaceResponse) {}
変更した

2022-11-11 16:52 UTC, hutinoatari commented on proto/spec/v1/userdata.proto
> +  rpc EraseRace(EraseRaceRequest) returns (EraseRaceResponse) {}
変更した

2022-11-12 04:49 UTC, Azuki-bar approved these changes
lgtm

2022-11-12 04:50 UTC, merged